spark.master                     local[*]
spark.sql.warehouse.dir          file:///E:/RetailPulseEnterprise/data/spark-warehouse
spark.eventLog.enabled           false
spark.sql.shuffle.partitions     16
spark.sql.adaptive.enabled       true
spark.serializer                 org.apache.spark.serializer.KryoSerializer
